create table if not exists public.inbound_leads (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('contact', 'playbook_request')),
  name text not null,
  email text not null,
  company text,
  message text,
  privacy_accepted boolean not null default false,
  created_at timestamptz not null default now()
);
